apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-name-hpa
  namespace: my-app-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-name-dep
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
