apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-name-cm
  namespace: {{ .Values.namespace }}
data:
  # overrided by deployment env variable
  QUARKUS_APP_CUSTOM_MESSAGE: "Hello from <<CONFIG_MAP>>."
