# kustomization.yaml contents
# https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app-ns-dev

resources:
- ../../base

commonLabels:
  env: dev

configMapGenerator:
- name: my-app-name-cm
  files:
  - config-map.conf