apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-kustomize-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: my-app-ns-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: kustomize/overlays/dev
    repoURL: https://github.com/viniciusfcf/gitops-examples.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true