apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-helm
  namespace: openshift-gitops
spec:
  destination:
    namespace: my-app-ns-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: my-app-name
    repoURL: https://viniciusfcf.github.io/charts
    targetRevision: 0.0.2
    helm:
      releaseName: my-app-name
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true